
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/RNReactNativeRichTextEditorViewSpec/EventEmitters.h>
#include <react/renderer/components/RNReactNativeRichTextEditorViewSpec/Props.h>
#include <react/renderer/components/RNReactNativeRichTextEditorViewSpec/ReactNativeRichTextEditorState.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook::react {

JSI_EXPORT extern const char ReactNativeRichTextEditorComponentName[];
/*
 * `ShadowNode` for <ReactNativeRichTextEditorComponentName> component.
 */
class ReactNativeRichTextEditorShadowNode final : public ConcreteViewShadowNode<
    ReactNativeRichTextEditorComponentName,
    ReactNativeRichTextEditorViewProps,
    ReactNativeRichTextEditorViewEventEmitter,
    ReactNativeRichTextEditorState> {
  public:
  using ConcreteViewShadowNode::ConcreteViewShadowNode;
};


} // namespace facebook::react
