
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "RNEnrichedTextInputViewSpec.h"

namespace facebook::react {

static facebook::jsi::Value __hostFunction_NativeEnrichedTextInputModuleSpecJSI_getHTMLValue(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, StringKind, "getHTMLValue", "(D)Ljava/lang/String;", args, count, cachedMethodId);
}

NativeEnrichedTextInputModuleSpecJSI::NativeEnrichedTextInputModuleSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["getHTMLValue"] = MethodMetadata {1, __hostFunction_NativeEnrichedTextInputModuleSpecJSI_getHTMLValue};
}

std::shared_ptr<TurboModule> RNEnrichedTextInputViewSpec_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
  if (moduleName == "EnrichedTextInputModule") {
    return std::make_shared<NativeEnrichedTextInputModuleSpecJSI>(params);
  }
  return nullptr;
}

} // namespace facebook::react
