export { EnrichedTextInput } from './native/EnrichedTextInput';
export type {
  EnrichedInputStyle,
  EnrichedTextInputProps,
  OnChangeTextEvent,
  OnChangeHtmlEvent,
  OnChangeStateEvent,
  OnLinkDetected,
  OnMentionDetected,
  OnChangeSelectionEvent,
  OnKeyPressEvent,
  OnPasteImagesEvent,
  OnSubmitEditing,
  HtmlStyle,
  MentionStyleProperties,
  FocusEvent,
  BlurEvent,
  EnrichedTextInputInstance,
  ContextMenuItem,
  OnChangeMentionEvent,
} from './types';
